# Generated by Django 2.1 on 2018-10-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_auto_20181020_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
